import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { CosmosProvider } from "../providers/chain-provider";
import "@interchain-ui/react/styles";
import { QueryProvider } from "@/providers/query-provider";
import { ConnectionWrapper } from "@/wrappers/connection-wrapper";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Dutch Auction",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <CosmosProvider>
          <QueryProvider>
            <ConnectionWrapper>{children}</ConnectionWrapper>
          </QueryProvider>
        </CosmosProvider>
      </body>
    </html>
  );
}
